---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
    name: meminfo-deployment
spec:
    replicas: 1
    template:
        metadata:
          labels:
            app: meminfo-large-test
        spec:
          containers:
            - name: meminfo-large-test
              image: mkrolik/snap-pytest:v1
              imagePullPolicy: "IfNotPresent"
              command:
              - sleep
              - "3000"