version: '2'
services:
  main:
    container_name: runner
    image: mkrolik/snap-pytest:v1
    environment:
     - SNAP_VERSION=latest
    volumes:
      - ${PLUGIN_SRC}:/snap-plugin-collector-meminfo
      - /proc:/var/procfs
    network_mode: "host"