version: '2'
services:
  main:
    container_name: meminfo_large_test
    image: python:2.7.12-alpine
    network_mode: "host"
    volumes:
      - ${PLUGIN_SRC}:/${PROJECT_NAME}
    entrypoint: sh -c 'python /${PROJECT_NAME}/scripts/test/large.py'
    environment:
      PROJECT_DIR: /${PROJECT_NAME}